experiment_name: 'sid'
data_path: "/home/ubuntu/dataset/artist20/chunk"
sr: 16000
model: 'ssl'
epoch: 10
batch_size: 48
length: 5
savename: 'exp.pt'
lr: 3e-4
url: "microsoft/wavlm-base-plus"
# fp: '32' # allow '32', 'bf16', '16'
freeze_all: False
early_stop: False