experiment_name: 'sid'
data_path: "/home/ubuntu/dataset/artist20np"
sr: 16000
model: 'crnn'
epoch: 50
batch_size: 32
length: 5
savename: 'exp.pt'
lr: 3e-4
url: "microsoft/wavlm-base-plus"
fp: '32' # allow '32', 'bf16', '16'